MM-28113 - Frontend UI updates
mattermost/mattermost-plugin-incident-response pull request #262
Opened 2020-08-27 13:03 UTC by asaadmahmood

#### Summary
https://mattermost.atlassian.net/browse/MM-28113

- [x] Missing remove optional description for task
- [x] Clicking either the title or pencil icon can edit the title
- [x] Stage and steps should be left-aligned rather than indented
- [x] Section heading says “Stages and steps”, should be “Stages and tasks”
- [x] Add Image to assigned item in Task
- [x] Move run button to the left 
- [x] Clicking the empty area to the right of step description also clicks the button
- [x] Clicking the empty area to the right of steps deletes the step
- [x] RHS missing help text for incident channel
- [x] RHS says “Channel type” rather than “Incident Channel”
- [x] Should have trash icon on hover
- [x] RHS has placeholder image but should be blank
- [x] Playbook background is not grey
- [x] Playbooks first in the header, and then Incidents
- [x] Add Close button in the header for Playbooks area

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28113

#### Screenshots
![localhost_8065_mattermost_com mattermost plugin-incident-response_playbooks_wpis6wxy3tb4xfrrcyu1ohjd8e (2)](https://user-images.githubusercontent.com/11034289/91445408-83f41400-e88f-11ea-93e7-e34a30114f8d.png)
![localhost_8065_mattermost_com mattermost plugin-incident-response_playbooks_wpis6wxy3tb4xfrrcyu1ohjd8e (1)](https://user-images.githubusercontent.com/11034289/91445412-85bdd780-e88f-11ea-8f03-0e1f5fcea1d4.png)

2020-08-27 13:50 UTC, asaadmahmood commented
@lieut-data Can you refresh, everything there should actually be left aligned.

2020-08-27 13:51 UTC, asaadmahmood commented
It should actually look like this.
![localhost_8065_mattermost_com mattermost plugin-incident-response_playbooks_wpis6wxy3tb4xfrrcyu1ohjd8e (3)](https://user-images.githubusercontent.com/11034289/91450885-3d55e800-e896-11ea-95be-046e398e4d6e.png)

2020-08-27 13:51 UTC, lieut-data commented
Oh, fascinating -- another one of those "old CSS left behind bugs." Yes, working here now!

2020-08-27 17:29 UTC, agarciamontoro requested changes
This is great! Thank you for the buttons components, they will come in handy!

I left a minor nit below, and found some old "step" wording here and there:
- `New Step` should be `New Task`  in stage_edit.tsx
- `Step Name` should be `Task Name` in step_edit.tsx
- `Steps` should be `Tasks` in playbook_list.tsx

2020-08-27 17:29 UTC, agarciamontoro commented on webapp/src/components/backstage/drag_handle.tsx
> +    task: boolean;
Can this be step? Just to be consistent with the code.

2020-08-27 19:26 UTC, lieut-data commented
All good points, @agarciamontoro -- I've pushed the requested changes.

2020-08-27 20:59 UTC, lieut-data commented
@asaadmahmood, I've additionally resolved, assuming that was just to reflect the incident name in the channel header
[x]  Adjust incident inner header to match designs.

<img width="409" alt="image" src="https://user-images.githubusercontent.com/1023171/91494314-06300880-e88f-11ea-8853-3553e1a8ac2e.png">

<img width="414" alt="image" src="https://user-images.githubusercontent.com/1023171/91494336-0cbe8000-e88f-11ea-8808-4dac0abc19a7.png">

2020-08-28 08:12 UTC, agarciamontoro approved these changes
Neat!

2020-08-28 13:07 UTC, merged