MM-27005 - Unit Test SQL Incident Store
mattermost/mattermost-plugin-incident-response pull request #268
Opened 2020-09-02 22:57 UTC by cpoile

#### Summary
- Pretty self explanatory. 
- Many thanks to @agarciamontoro, much of this is his hard work (especially getting the framework set up)

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-27005

2020-09-03 12:22 UTC, lieut-data requested changes
A handful of comments -- thanks, @cpoile!

2020-09-03 12:22 UTC, lieut-data commented on server/incident/filter_options.go
> +		options.Sort = "CreateAt"
No need to block here, but I think this "mapping" from the API sort values to the database sort values doesn't belong here. It's an internal detail of the SQLStore, and shouldn't really be exposed outside it.

2020-09-03 12:22 UTC, lieut-data commented on server/sqlstore/incident.go
> +	if len(incidents) == 0 {
An empty list and a `nil` list are semantically equivallent: except when we serialize to JSON. As such, this feels like a concern outside of the scope of the `sqlstore` package. Should we "deal" with this in the api package instead?

2020-09-03 12:22 UTC, lieut-data commented on server/sqlstore/incident.go
> +	incidentCopy := *newIncident
This is only a shallow copy -- are there fields remaining in the `Incident` that will still be shared with the copied object? Should we formalize this by adding a `Clone` method?

2020-09-03 12:22 UTC, lieut-data commented on server/sqlstore/incident.go
> +		if !added[c.CommanderUserID] && options.HasPermissionsTo != nil && options.HasPermissionsTo(c.ChannelID) {
Maybe just add a `DISTINCT` to the query instead?

2020-09-03 12:22 UTC, lieut-data commented on server/sqlstore/migrations.go
> +						ChecklistsJSON TEXT NOT NULL,
With this change, do we still need to have two `CREATE TABLE` invocations? (Fine if we do, just checking :))

2020-09-03 12:22 UTC, lieut-data commented on server/sqlstore/migrations.go
> +					CREATE EXTENSION IF NOT EXISTS unaccent;
This may not be a permission we can rely upon -- is there something built-in that we could do instead?

2020-09-03 14:36 UTC, cpoile commented on server/incident/filter_options.go
> +		options.Sort = "CreateAt"
Agreed, small ticket for that: https://mattermost.atlassian.net/browse/MM-28318

2020-09-03 14:37 UTC, cpoile commented on server/pluginkvstore/incident_store.go
> +	case "ID":
👍 Added to ticket above.

2020-09-03 15:11 UTC, cpoile commented on server/sqlstore/incident.go
> +	if len(incidents) == 0 {
It is handled in the API... after looking at this, I realize what's happening. The original kvstore tests are expecting a `[]incident.Incident(nil)`, but this is returning a `[]incident.Incident{}`, and that's why Alejandro added this check here. But it's only returning an `[]incident.Incident{}` because we do paging after, and that will return a `[]incident.Incident{}` if there are no incidents in the page. Anyway, no big deal, I just changed the tests.

2020-09-03 15:26 UTC, cpoile commented on server/sqlstore/incident.go
> +	incidentCopy := *newIncident
Yep, you're right (bc of the slices). Done!

2020-09-03 16:23 UTC, cpoile commented on server/sqlstore/incident.go
> +		if !added[c.CommanderUserID] && options.HasPermissionsTo != nil && options.HasPermissionsTo(c.ChannelID) {
I'm not sure if you can, unless you can think of a way? What if you have CommanderA on channel1, and CommanderA for channel2, but the person doing this request only has permissions to channel2?

2020-09-03 16:35 UTC, cpoile commented on server/sqlstore/migrations.go
> +						ChecklistsJSON TEXT NOT NULL,
I think we do want separate invocations, unless we want to move the Postgres "ideal" `TEXT` columns into the MySQL `VARCHAR(26/1024/etc)` columns. If we're fine with that, we could make it a single `create table` -- up to you. I'm 1/5 to keep them separate, for no reason other than I like doing 'the right thing' for Postgres.

2020-09-03 16:49 UTC, cpoile commented on server/sqlstore/migrations.go
> +					CREATE EXTENSION IF NOT EXISTS unaccent;
Sorry, not sure what you mean here. Do you mean the unaccent extension? I'm not exactly sure why it is added here (that's Alejandro), but it looks like it's included in Postgres since at least 9.1, so we should always have it. Did you mean something else?

2020-09-03 16:57 UTC, lieut-data commented on server/sqlstore/incident.go
> +		if !added[c.CommanderUserID] && options.HasPermissionsTo != nil && options.HasPermissionsTo(c.ChannelID) {
Ah, yes -- this would be blocked on the permission being inlined. Once that's done, should tidy up nicely!

2020-09-03 16:58 UTC, lieut-data commented on server/sqlstore/migrations.go
> +					CREATE EXTENSION IF NOT EXISTS unaccent;
I mean that invoking `CREATE EXTENSION` may not be a permission granted to the `mattermost` user. Just wondering how dependent we are on this.

2020-09-03 17:01 UTC, cpoile commented on server/sqlstore/migrations.go
> +					CREATE EXTENSION IF NOT EXISTS unaccent;
Is it okay if we wait for Alejandro to answer that -- I'll create a ticket for him to look into it. https://mattermost.atlassian.net/browse/MM-28332

2020-09-03 17:02 UTC, cpoile commented
Changes are up, still not sure about the CircleCI tests -- I'll work on them this afternoon I guess (would be nice to have them working)

2020-09-03 17:03 UTC, lieut-data approved these changes

2020-09-03 20:49 UTC, cpoile commented
@lieut-data Got the sql testing to work with circleci.

2020-09-04 14:10 UTC, cpoile commented
Will merge now so I can rebase and work on the playbook store tests -- all that changed since last review was the circleci config, we can iterate on that later. Thanks!

2020-09-04 14:10 UTC, merged