MM-27006 - Unit test the playbook store
mattermost/mattermost-plugin-incident-response pull request #270
Opened 2020-09-04 14:06 UTC by cpoile

#### Summary
- WIP

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-27006

2020-09-08 13:03 UTC, lieut-data requested changes
Super cool! A few comments, mostly around the supporting changes rather than the tests themselves.

2020-09-08 13:03 UTC, lieut-data commented on server/sqlstore/playbook.go
> +	delBuilder := sq.Delete("IR_PlaybookMember").
It's probably not terribly important right now, but it's generally quite "thrashy" to delete all and re-insert every time, given the tombstoning of records and such. Would suggest something more like `DELETE FROM IR_PlaybookMember WHERE PlaybookId = :ID and UserID NOT IN (:member_ids)`, syntax issues aside.

2020-09-08 13:03 UTC, lieut-data commented on server/sqlstore/playbook.go
> +			return nil, errors.New("checklists with no items are not allowed")
As a random aside, I think it would be as simpler UI experience if we just allowed empty checklists, since the frontend doesn't make it super clear "what's wrong" when this happens anyway.

2020-09-08 21:02 UTC, cpoile commented on server/sqlstore/incident.go
> +		if err != nil {
Ok, sounds good. Done!

2020-09-08 21:02 UTC, cpoile commented on server/sqlstore/incident.go
> +func checklistsToJSON(checklists []playbook.Checklist) (json.RawMessage, error) {
Yep, makes sense. That's a bit of a bug on my part, although you'd never know with the way we use pointers in parameters...
We're now passing in an `incident.Incident` (not a pointer). I've never liked how we pass around pointers in the incident package. But I haven't made any changes to the interface; I would want everyone's input on that to see if other people agree with me or not.

2020-09-08 21:02 UTC, cpoile commented on server/sqlstore/incident_test.go
> +		for _, tt := range testData {
Either way is fine with me, made the change. :)

2020-09-08 21:02 UTC, cpoile commented on server/sqlstore/playbook.go
> +			"Stages":               len(rawPlaybook.Checklists),
Yep we need it for query time to sort by Stages or Steps -- this will require a change to our validation (to turn `Stages` into `NumStages`. Will do.

2020-09-08 21:02 UTC, cpoile commented on server/sqlstore/playbook.go
> +// GetPlaybooks retrieves all playbooks that are not deleted. Does not return Checklists
I'm not sure, because the only method that does return the checklist is the straight `Get` -- we'd have to change the name of all the `GetPlaybooks*` methods (granted, there's only two...). Maybe just remove that comment?

2020-09-08 21:02 UTC, cpoile commented on server/sqlstore/playbook.go
> +	} else if playbook.IsValidSortBy(opts.Sort) {
We do a validation in the API layer in `parseGetPlaybooksOptions`. Are you sure we should double that here as well? Or can we assume that if the request made it through the API layer (or was called directly), we don't have to return errors on invalid options?

2020-09-08 21:02 UTC, cpoile commented on server/sqlstore/playbook.go
> +	if err == sql.ErrNoRows || len(out) == 0 {
Right, good catch. That is how it should work.

2020-09-08 21:02 UTC, cpoile commented on server/sqlstore/playbook.go
> +	delBuilder := sq.Delete("IR_PlaybookMember").
Great, the delete was doable. Sorry it took so long, but I found that the "insert if not exists" is tricky for Postgres pre 9.5. So I did it manually for now. 
As an aside, I'm a little frustrated using squirrel for anything other than what it's built to accommodate. Anything unusual and you're trying to both get the SQL right and find out how to mangle it in the way that squirrel expects.

2020-09-08 21:02 UTC, cpoile commented on server/sqlstore/playbook.go
> +			return nil, errors.New("checklists with no items are not allowed")
Should we make a ticket for Asaad?

2020-09-09 12:14 UTC, lieut-data commented on server/sqlstore/playbook.go
> +	} else if playbook.IsValidSortBy(opts.Sort) {
I don't think we should too much about the origin of the data being passed in here. That being said, discarding is a valid and safe approach for now, which we can revisit if we ever have clients other than the api package.

2020-09-09 12:15 UTC, lieut-data commented on server/sqlstore/playbook.go
> +	delBuilder := sq.Delete("IR_PlaybookMember").
Hmm, can you elaborate on the Squirrel challenges? Generally speaking, you can drop into SQL at any time (including for subqueries), so perhaps we should just do that more often?

2020-09-09 12:38 UTC, lieut-data approved these changes
A few thoughts, but not strictly blocking I think.

2020-09-09 12:38 UTC, lieut-data commented on server/sqlstore/incident.go
> +	rawIncident, err := toSQLIncident(*newIncident)
I'm not sure passing the value here is any "safer" -- the internal `Checklists` is still a pointer, and still subject to potential mutation. It now seems hard to realize this than when it was unambiguously a pointer. Thoughts?

(I realize we appear to copy it correctly down the stack, so I don't think there's an actual bug here.)

2020-09-09 12:38 UTC, lieut-data commented on server/sqlstore/playbook.go
> +func (p *playbookStore) replacePlaybookMembers(q queryer, e execer, pbook playbook.Playbook) error {
Squirrel defines a `BaseRunner` that embeds both `Execer` and `Queryer` -- should we define a variant for ourselves and accept that here instead to avoid the illusion that we could pass distinct transactions (to separate databases, even)?

2020-09-09 12:38 UTC, lieut-data commented on server/sqlstore/playbook.go
> +	// Now, only add new members
Would something like this help, assuming we just ran a prepared query multiple times vs. binding multiple input parameters?
```sql
INSERT INTO IR_PlaybookMember(PlaybookID, MemberID)
    SELECT :PlaybookId, :MemberId
    WHERE NOT EXISTS (
        SELECT 1 FROM IR_PlaybookMember WHERE PlaybookId = :PlaybookID AND MemberID = :MemberId
    );
```

2020-09-09 13:27 UTC, cpoile commented on server/sqlstore/incident.go
> +	rawIncident, err := toSQLIncident(*newIncident)
Sorry, I should have been clearer -- I meant: to me if a parameter is a pointer it implies that the parameter can be changed within the function (maybe I'm thinking C, but that's what I always think when I see that). So yah, it's not any "safer", but it does read more clearer (at least for me) -- as long as the function obeys that convention. But I'm not sure what the Go standards are... Are there any conventions about that?

2020-09-09 13:27 UTC, cpoile commented on server/sqlstore/playbook.go
> +func (p *playbookStore) replacePlaybookMembers(q queryer, e execer, pbook playbook.Playbook) error {
Yep, that's much better, thank you!

2020-09-09 13:27 UTC, cpoile commented on server/sqlstore/playbook.go
> +	// Now, only add new members
I was looking at that too, but what stopped me was: if we're thinking of doing this to prevent thrashing (in other words, for performance) then wouldn't it be orders of magnitude more performant to prepare all the values ahead of time and make one call to the db?

2020-09-09 14:11 UTC, lieut-data commented on server/sqlstore/playbook.go
> +	// Now, only add new members
My concern with thrashing in his case was relative to writes -- deleting all the rows and inserting them again is effectively `2N` writes in terms of the number of members. Writes are orders of magnitude more expensive than selects, given the eventual write to disk, cache invalidations, etc. So a handful of `SELECT`s would still be way better than writes.

In terms of the number of calls -- a prepared query that's executed multiple times inside a transaction is roughly equivalent to a single call binding a ton of parameters. That is, the actual number of `Execute()` calls isn't necessarily something to optimize. In this case, pulling the existing members down in order to decide which ones to send back might be as expensive as sending every member back for the database to ignore some. (That is, the number of bits across the wire is about the same -- when statements are prepared.)

2020-09-09 14:26 UTC, lieut-data commented on server/sqlstore/incident.go
> +	rawIncident, err := toSQLIncident(*newIncident)
I think Go's default position is pass-by-value, unless you need to mutate or you've measured performance issues that passing by pointer helps address. But it's not as "idiomatic" as some of the other guidance I've seen. 0/5 on either direction here.

2020-09-09 14:26 UTC, lieut-data approved these changes

2020-09-09 16:12 UTC, cpoile commented on server/sqlstore/playbook.go
> +	// Now, only add new members
Okay, I tried to make it work with Squirrel, but I can't seem to find a way to build the `SELECT ?, ?` statement. I looked at all the squirrel tests, and they don't test for it, so I'm guessing they can't do it. And since it doesn't have a Values clause, it fails to build. So I just went to raw SQL. /shrug

2020-09-09 16:19 UTC, lieut-data approved these changes

2020-09-09 16:52 UTC, merged