MM-28008 - Permissions checking in SQL; use subqueries
mattermost/mattermost-plugin-incident-response pull request #277
Opened 2020-09-13 16:34 UTC by cpoile

#### Summary
- This is why we moved to SQL
- moves permission checking into the sql calls for playbooks and incidents. 
- huge speedup; for playbooks we went from 8.6s -> 49ms, for incidents we go from 1 minute -> 84ms (on a stress test of ~4400 incidents and 1000 playbooks).

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-28008
- https://mattermost.atlassian.net/browse/MM-28149
- https://mattermost.atlassian.net/browse/MM-26698

2020-09-13 16:37 UTC, cpoile commented
/update-branch

2020-09-14 18:07 UTC, crspeller requested changes

2020-09-14 18:07 UTC, crspeller commented on server/playbook/filter_options.go
> +	HasPermissionsTo func(pb Playbook, userID string) bool
This is the kind of weird stuff you get when we do backwards compatibility. It confused me a bit why we needed this if we had switched to the queries... but then I remembered.

2020-09-14 18:07 UTC, crspeller commented on server/sqlstore/incident.go
> +	isAdminOrMemberOrPublicChannelSQLText = `
This query isn't perfect. It gives broader permissions then previously granted. For example, a guest user is a member of the team and there might be open incident channels, but you might not want them to see them. 

I think we might need to actually copy the permissions queries from the server.

2020-09-14 18:23 UTC, cpoile commented on server/sqlstore/incident.go
> +	isAdminOrMemberOrPublicChannelSQLText = `
I agree, we should define the exact permissions -- @lieut-data can you help with this?
For guests, we could a `not guest` check, if we do want to limit guests to not seeing public incidents. Is that what we want?

What we actually do is:
1. check if you're a system admin; if not try:
1. check if you have permission to read channel; if not try:
1. check if the channel is public and if you can "LIST_TEAM_CHANNELS". 

It's the `LIST_TEAM_CHANNELS` that I'm somewhat guessing on.

But I'm unclear on what the exact permissions we were using. Because I tried tracing the permissions in the server code, and it's not clear what's happening when you get into `mergeChannelHigherScopedPermissions`.

2020-09-14 18:24 UTC, cpoile commented on server/playbook/filter_options.go
> +	HasPermissionsTo func(pb Playbook, userID string) bool
Yah. I'm not sure when we'll pull out all that code, so I had to make sure it still worked even with the refactoring.

2020-09-15 11:38 UTC, agarciamontoro requested changes
The speedups are amazing, the change was indeed worth it!

I left some comments below, mostly nits.

2020-09-15 11:38 UTC, agarciamontoro commented on server/playbook/playbook.go
> +	GetPlaybooksForTeam(requester, teamID string, opts Options) (GetPlaybooksResults, error)
Nit: can this be `requesterID`, just for consistency?

2020-09-15 11:38 UTC, agarciamontoro commented on server/sqlstore/playbook.go
>  	}
This is perfect, but I had to double check what was happening with `p.MemberIDs`, because we are only appending `p.Playbook` to`ret`. Of course, the `p.MemberIDs` is part of `p.Playbook`, but it is a bit confusing (this is Go's fault, not yours).

2020-09-15 11:38 UTC, agarciamontoro commented on server/sqlstore/playbook.go
> +	if opts.Page <= 0 {
The nittiest nit you can imagine:
```suggestion
	if opts.Page < 0 {
```

2020-09-15 11:38 UTC, agarciamontoro commented on server/sqlstore/support_for_test.go
> +		require.NoError(t, err)
This was left here after the refactor, but I think it only belongs in `setupChannelMemberHistoryTable`.

2020-09-15 11:38 UTC, agarciamontoro commented on server/sqlstore/incident.go
> +	isAdminOrMemberOrPublicChannelSQLText = `
Also, can we change this into a function, so we can call something like `buildPermissionsWhereExpr(requesterID, opts.TeamID)`? This would prevent the need to look into the position of the parameters in this string, and we can rely on the function parameteres.

2020-09-15 11:41 UTC, agarciamontoro commented on server/sqlstore/playbook.go
>  	}
(I wrote this in an earlier commit, but the comment still applies after the latest changes)

2020-09-15 14:09 UTC, cpoile commented on server/sqlstore/playbook.go
>  	}
Ok, makes sense -- code for clarity while reading, not for terseness. Fixed. :)

2020-09-15 14:09 UTC, cpoile commented on server/sqlstore/playbook.go
> +	if opts.Page <= 0 {
That's pretty nitty, but I'll own it. Fixed. 😂

2020-09-15 14:09 UTC, cpoile commented on server/sqlstore/support_for_test.go
> +		require.NoError(t, err)
Ah yes, missed that. Thanks.

2020-09-15 14:10 UTC, cpoile commented on server/sqlstore/incident.go
> +	isAdminOrMemberOrPublicChannelSQLText = `
That's a great idea! Done.

2020-09-15 14:13 UTC, agarciamontoro approved these changes
Great, thank you! :tada:

2020-09-15 14:14 UTC, lieut-data reviewed
Apologies, I had typed up a bunch of comments yesterday but didn't have time to finish a detailed SQL review. I'm posting them now, knowing that some have already been raised, and then will do a second pass to get through the SQL and respond to the "queries" above (pun intended ;P).

2020-09-15 14:18 UTC, lieut-data commented on server/sqlstore/incident.go
> +	isAdminOrMemberOrPublicChannelSQLText = `
On the issue of building the query, I think we can pre-flight / use-the-api to check the admin and guest bits and make decisions accordingly. (If guest, then only check channel membership, not `LIST_TEAM_CHANNELS`).

Would that simplify things?

2020-09-15 14:32 UTC, cpoile commented on server/sqlstore/incident.go
> +	isAdminOrMemberOrPublicChannelSQLText = `
@lieut-data It's an interesting solution, but I think it might end up causing more complication---if we use the api to check for system admin and guest, then we're sending those bits and pushing the logic into the sqlstore, which has to build a custom query based on those bits. I think it might be simpler to add the guest check in the SQL. Then we use the same permissions logic for every query.

2020-09-15 14:37 UTC, cpoile commented on server/sqlstore/incident.go
> +	isAdminOrMemberOrPublicChannelSQLText = `
Or I could be wrong, and it's simpler to build it up... How about I'll try both and we'll see?

2020-09-15 14:40 UTC, lieut-data commented on server/sqlstore/incident.go
> +	isAdminOrMemberOrPublicChannelSQLText = `
Yeah, that's fair. It will be especially good if we can replicate precisely what the server is doing here.

2020-09-15 15:54 UTC, cpoile commented on server/sqlstore/incident.go
> +	isAdminOrMemberOrPublicChannelSQLText = `
From our discussion in sprint planning: do the tests first, then send the permissions over to the sqlstore.

2020-09-15 15:58 UTC, cpoile commented on server/api/playbooks.go
> +	opts.HasPermissionsTo = h.hasPermissionsToPlaybook
Yep, this'll be removed in the-big-kvstore-removal PR. :)

2020-09-15 21:40 UTC, cpoile commented on server/incident/filter_options.go
> +	case OrderAsc, "": // default (like in SQL)
It mattered because while I was writing the tests I had to keep remembering what the default ordering was, and it was different from the playbookStore's. So I wanted to make them consistent, and chose asc because I bet it's what people would expect as the default. I will remove the comment though, since you're right it doesn't really matter that SQL does it like this.

2020-09-15 21:40 UTC, cpoile commented on server/pluginkvstore/incident_store.go
> +	result := []incident.Incident{}
This is just for the kvstore. I just made a change to return nil and do the empty slice conversion in the api layer. :)

2020-09-15 21:41 UTC, cpoile commented on server/sqlstore/incident.go
> +	isAdminOrMemberOrPublicChannelSQLText = `
Yep, done!

2020-09-15 21:41 UTC, cpoile commented on server/sqlstore/incident.go
> +                         WHERE u.Id = ?
No need now, there's only one parameter. But I checked, and it doesn't look like it lets you--it's not in the docs (such as they are) and I couldn't find an example of named parameters in the tests.

2020-09-15 21:41 UTC, cpoile commented on server/sqlstore/incident.go
> +                              AND cm.UserId = ?)
Nope, I traced the code -- the row is deleted. (As you know, we keep track of past membership in the history table.)

2020-09-15 21:42 UTC, cpoile commented on server/sqlstore/incident.go
> +                      EXISTS(SELECT 1
Not needed now -- we test for CanViewTeamChannels, and if they can then all we need to test for is whether the channel is open.

2020-09-15 21:42 UTC, cpoile commented on server/sqlstore/incident.go
> +                                   AND c.Type = 'O')
At the moment we don't have that restriction -- you can still list and view details of and even visit incident channels that have been archived. Is there another level of Delete that I haven't encountered yet?

2020-09-15 21:42 UTC, cpoile commented on server/sqlstore/incident.go
> +                                       AND t.UserId = ?)
Removed now, so not needed.

2020-09-15 21:42 UTC, cpoile commented on server/sqlstore/incident.go
> +		From("IR_Incident AS inc")
Yep, I didn't like that either -- I kept thinking it was "increment" which is what Clojure uses all the time.

2020-09-15 21:42 UTC, cpoile commented on server/sqlstore/incident.go
> +		requesterID, requesterID, opts.TeamID, requesterID)
Yep, not needed anymore. :)

2020-09-15 21:42 UTC, cpoile commented
/update-branch

2020-09-16 14:52 UTC, lieut-data requested changes
Nice work, @cpoile! A few follow up questions.

2020-09-16 14:52 UTC, lieut-data commented on server/api/incidents.go
> +		CanViewTeamChannels: permissions.CanViewTeam(userID, filterOptions.TeamID, h.pluginAPI),
nit: we don't "remember" the `TeamID` here, so `CanViewTeamChannels` can be a but worrisome as a general flag. Maybe a `map[string]bool` to make this explicit and safe by default?

2020-09-16 14:52 UTC, lieut-data commented on server/sqlstore/support_for_test.go
> +	// Statements copied from mattermost-server/scripts/mattermost-postgresql-5.0.sql
If we copied from here, this schema is "out of date" relative to v5.28 (by over two years). Possibly not an issue for now.

2020-09-16 14:52 UTC, lieut-data commented on server/sqlstore/playbook.go
> +                         AND u.Roles LIKE '%system_admin%')
Should we have a requester info that passes the `isAdmin` as well?

2020-09-16 14:52 UTC, lieut-data commented on server/sqlstore/playbook.go
> +		Join(getMembers).
nit: I find this embedded `getMembers` to be much harder to parse than the original two queries. It seems like a modest performance difference between the two implementations?

2020-09-16 14:52 UTC, lieut-data commented on server/sqlstore/playbook.go
> +		(
Is this parenthesis necessary? Wondering if `WHERE` from the builder will do the right thing by itself?

2020-09-16 14:52 UTC, lieut-data commented on server/sqlstore/playbook.go
> +                                 AND t.UserId = ?)
Check `DeleteAt`?

2020-09-16 14:52 UTC, lieut-data commented on server/sqlstore/incident.go
> +func (s *incidentStore) GetIncidents(requesterInfo incident.RequesterInfo, opts incident.HeaderFilterOptions) (*incident.GetIncidentsResults, error) {
nit: why `opts` from `options`?

2020-09-16 14:52 UTC, lieut-data commented on server/sqlstore/incident.go
> +		incidents[i].Checklists = []playbook.Checklist{}
Why is this necessary?

2020-09-16 14:52 UTC, lieut-data commented on server/sqlstore/incident.go
> +		Select("DISTINCT CommanderUserID AS UserID", "Username").
nit: propose always namespacing the columns when there are multiple being selected, so `incident.CommandUserID` and `u.Username` (or just `u.Id` and `u.Username`).

2020-09-16 14:52 UTC, lieut-data commented on server/sqlstore/incident.go
> +		commanders = []incident.CommanderInfo{}
nit: this is similar to a comment of my above, but ideally shouldn't be necessary at this layer.

2020-09-16 14:52 UTC, lieut-data commented on server/sqlstore/incident.go
> +						 WHERE cm.ChannelId = incident.ChannelID
Check for channel membership deletion?

2020-09-16 16:38 UTC, cpoile commented on server/api/incidents.go
> +		CanViewTeamChannels: permissions.CanViewTeam(userID, filterOptions.TeamID, h.pluginAPI),
Not sure what you mean here by remembering the `TeamID`, and why that would affect the `CanViewTeamChannels` flag...?

2020-09-16 16:40 UTC, cpoile commented on server/sqlstore/support_for_test.go
> +	// Statements copied from mattermost-server/scripts/mattermost-postgresql-5.0.sql
Right -- at this point all we need are the few fields that we check in the tests, so none of the changes up to 5.28 will affect it. I left Alejandro's comment here because it's good to remind people that it's an old schema, and if they run into a mismatch and can't run the tests, that's why. I'll add a comment to that effect.

2020-09-16 17:30 UTC, cpoile commented on server/sqlstore/playbook.go
> +                         AND u.Roles LIKE '%system_admin%')
Yep, I made playbooks consistent with how we do it in incident.

2020-09-16 17:32 UTC, cpoile commented on server/sqlstore/playbook.go
> +		Join(getMembers).
Sorry, I'm not following -- we use `Join(getMembers)` the same way in both `queryForResults` and `queryForTotal`, what original two queries do you mean?

> It seems like a modest performance difference between the two implementations?

Also not sure what you mean here.

2020-09-16 17:35 UTC, cpoile commented on server/sqlstore/playbook.go
> +		(
It didn't because Postgres doesn't like the way Squirrel `or`s `exists` statements. But either way, it doesn't matter -- with the `requesterInfo` these checks reduce to one `exists` statement, which is fine for both dbs, so I converted it to a builder statement. :)

2020-09-16 17:36 UTC, cpoile commented on server/sqlstore/playbook.go
> +                                 AND t.UserId = ?)
I thought I commented about that before? (maybe it got lost by Github?) Anyway, it's moot since we're using the `requesterInfo` and we don't need this check anymore.

2020-09-16 17:38 UTC, cpoile commented on server/sqlstore/incident.go
> +func (s *incidentStore) GetIncidents(requesterInfo incident.RequesterInfo, opts incident.HeaderFilterOptions) (*incident.GetIncidentsResults, error) {
To be consistent with the `GetCommanders` parameter name -- I'm 0/5, so I changed them both to `options`.

2020-09-16 17:47 UTC, cpoile commented on server/sqlstore/incident.go
> +		incidents[i].Checklists = []playbook.Checklist{}
It's the frontend expecting an array problem. I moved this to the api. :)

2020-09-16 18:09 UTC, cpoile commented on server/sqlstore/incident.go
> +						 WHERE cm.ChannelId = incident.ChannelID
(also pretty sure I commented on this before) -- there's no DeleteAt column for these rows (we have ChannelMemberHistory)

2020-09-16 18:11 UTC, lieut-data commented on server/api/incidents.go
> +		CanViewTeamChannels: permissions.CanViewTeam(userID, filterOptions.TeamID, h.pluginAPI),
The `RequesterInfo` isn't self-contained. We compute a bit that is `CanViewTeamChannels` and assume that somewhere, downstream, someone is using that bit against the same `TeamID` that we used. It works that way right now, but lends itself to misuse IMO.

2020-09-16 18:13 UTC, lieut-data commented on server/sqlstore/playbook.go
> +		Join(getMembers).
Before, we appeared to collect all the playbook IDs, then query for the members discretely. Now we're using the aggregate functions to do that in "one query", but we have to deal with MySQL vs Postgres... and it seems complicated :)

2020-09-16 18:13 UTC, cpoile commented on server/api/incidents.go
> +		CanViewTeamChannels: permissions.CanViewTeam(userID, filterOptions.TeamID, h.pluginAPI),
Ah, I see what you mean. Hah, I never even thought about that. Sure, I'll make that change!

2020-09-16 18:14 UTC, lieut-data commented on server/sqlstore/playbook.go
> +                                 AND t.UserId = ?)
Sorry, it's not super obvious why requester info "guards" us against this -- I think the SQL queries should be reasonably "self-contained", and assuming that the user won't be deleted because we checked it upstream seems brittle.

2020-09-16 18:14 UTC, lieut-data commented on server/sqlstore/incident.go
> +						 WHERE cm.ChannelId = incident.ChannelID
Sounds good! Sorry, I definitely missed these :)

2020-09-16 18:22 UTC, lieut-data requested changes
Great, just spotted a permissions error.

2020-09-16 18:22 UTC, lieut-data commented on server/api/playbooks.go
> +		IsAdmin:             permissions.CanViewTeam(userID, teamID, h.pluginAPI),
`IsAdmin` !== `CanViewTeam`?

2020-09-16 18:22 UTC, lieut-data commented on server/command/command.go
> +		IsAdmin:             permissions.CanViewTeam(r.args.UserId, r.args.TeamId, r.pluginAPI),
See above.

2020-09-16 18:23 UTC, cpoile commented on server/api/playbooks.go
> +		IsAdmin:             permissions.CanViewTeam(userID, teamID, h.pluginAPI),
Shoot, I was too quick typing. Sorry, will fix.

2020-09-16 18:23 UTC, cpoile commented on server/command/command.go
> +		IsAdmin:             permissions.CanViewTeam(r.args.UserId, r.args.TeamId, r.pluginAPI),
Was a cut and paste from above. 🤕

2020-09-16 18:51 UTC, cpoile commented on server/sqlstore/playbook.go
> +		Join(getMembers).
Yah, I guess It's true, we're moving the complexity into the sql store, and there probably isn't a huge speedup... But it's so coooool. :P

Okay, I'll change it back -- priority should be readability and maintainability, not technical cleverness.  I'm going to save it though, it makes me happy.

2020-09-16 18:52 UTC, cpoile commented on server/sqlstore/playbook.go
> +                                 AND t.UserId = ?)
You're right, I guess we are assuming that if the user isAdmin or if the user CanViewTeam, then they aren't deleted and they should be given those permissions in the store layer.  But that's the same permissions sequence we used before. We never checked if the user was not deleted before, do we want to do that for every query now?  

I'm okay to do it, I just wonder what situation we're guarding against, which the previous kvstore implementation was not guarded against?

2020-09-16 19:37 UTC, cpoile commented
/update-branch

2020-09-16 19:42 UTC, lieut-data approved these changes

2020-09-16 19:42 UTC, lieut-data commented on server/api/incidents.go
> +		UserIDtoIsAdmin:     map[string]bool{userID: permissions.IsAdmin(userID, h.pluginAPI)},
I apologize for all the thrashing on this -- and please ignore this comment for the purpose of merging this PR.

I really like your solution of just adding `TeamID` to the struct. Then it's all grouped together -- `UserID`, `TeamID`, `IsAdmin`, `CanViewTeam` now all make sense in context. Hard to use "incorrectly."

But doing /both/ `TeamID` and a `TeamIDtoCanViewTeam` feels weird, since it's not a set of `TeamIDs` for which the request is being made, so I really don't need "support for one."

2020-09-16 19:44 UTC, cpoile commented on server/api/incidents.go
> +		UserIDtoIsAdmin:     map[string]bool{userID: permissions.IsAdmin(userID, h.pluginAPI)},
Ok, makes sense! I'll merge this and then fix this a bit later, but I understand now. :)

2020-09-16 19:44 UTC, merged