MM-28678 Cypress tests on CircleCI
mattermost/mattermost-plugin-incident-response pull request #278
Opened 2020-09-14 18:36 UTC by cpoile

#### Summary
- wip

#### Ticket Link

2020-09-14 21:47 UTC, cpoile commented
/update-branch

2020-09-14 22:08 UTC, cpoile commented
/update-branch

2020-09-14 23:22 UTC, cpoile commented
/update-branch

2020-09-15 14:35 UTC, cpoile commented
/update-branch

2020-09-15 14:46 UTC, lieut-data commented
🤯

2020-09-16 10:02 UTC, agarciamontoro requested changes
This is amazing, thank you! :pray: 

I see that the data in test_data.sql is from a dump, but I'm curious where that data comes from.

2020-09-16 16:21 UTC, lieut-data approved these changes
:+1: to @agarciamontoro's feedback, but otherwise LGTM.

2020-09-16 19:50 UTC, cpoile commented on .circleci/config.yml
> +            until curl --max-time 5 --output - localhost:9200; do echo waiting for Elasticsearch; sleep 5; done;
I'm hesitant to change it -- it's working, and this part is originally Saturn's. I don't mind if we wait a bit too long -- better than not waiting long enough. :)

2020-09-16 19:50 UTC, cpoile commented on server/sqlstore/data_migration.go
> +			}
Yep, that's a good idea! Done!

2020-09-16 19:51 UTC, cpoile commented
The dump comes from me running a fresh postgres install and running `make test-data`. Just to make sure we know exactly what data we're going to have.

2020-09-16 22:29 UTC, cpoile commented
@agarciamontoro Please merge this if you're happy with the changes!

2020-09-17 00:45 UTC, prapti approved these changes
Looks great! I tested the files where changes in `plugin_ui_command` would be used, and they all passed.
Thank you for doing this @cpoile!!

2020-09-17 00:45 UTC, prapti commented on tests-e2e/cypress/support/plugin_ui_commands.js
> +    cy.findByTestId('post_textbox').clear().type('another new message here{enter}');
It's strange and I don't know why this is needed, but all the tests are passing now so I don't want to dig into it right at this moment. I'll take a note of this for future cleanup.

2020-09-17 00:46 UTC, prapti commented
And just realized that I reviewed before @agarciamontoro finished his review. But if I need to review it again, please let me know :)

2020-09-17 07:29 UTC, agarciamontoro commented on .circleci/config.yml
> +            until curl --max-time 5 --output - localhost:9200; do echo waiting for Elasticsearch; sleep 5; done;
Sounds good!

2020-09-17 07:29 UTC, agarciamontoro commented on server/sqlstore/data_migration.go
> +			}
Thanks :)

2020-09-17 07:30 UTC, agarciamontoro approved these changes

2020-09-17 07:31 UTC, merged

2020-09-17 13:51 UTC, cpoile commented on tests-e2e/cypress/support/plugin_ui_commands.js
> +    cy.findByTestId('post_textbox').clear().type('another new message here{enter}');
@prapti I think it has something to do with the selector for last message -- if there's only one message in the channel,  that message won't have the exact format of id that the selector is looking for, so it just waits and waits and then fails.  But I could be wrong, please let me know what you uncover!