MM-28285: /incident list
mattermost/mattermost-plugin-incident-response pull request #291
Opened 2020-09-21 15:43 UTC by agarciamontoro

#### Summary

This PR adds a new slash command: `/incident list`. It lists the ongoing incidents of the current team, ordered by creation date (most recent first).

(I also needed to do a teeny tiny refactor in the `Ephemeral` function from bot.Poster, which is isolated in the first commit)

As predicted on the ticket, the final style (see the screenshots below) is quite different from the original designs:
- I used [Message Attachments](https://docs.mattermost.com/developer/message-attachments.html) to differentiate each incident. Styling with raw markdown was far from perfect, and the rendering of the message attachments (different in mobile and in the webapp) is more similar to the designs. The biggest difference is that each incident is enclosed within a box whose left side is coloured. But I do like it.
- As each incident is enclosed in a box, I did not add the horizontal lines separating them.
- The interactive button cannot be used, as it is designed to send data to the plugin, not to go to another location. Instead, the link to the channel is embedded in the incident name, which I styled as a title to make it easier to tap into it on mobile. I thought about adding a separate link with the text `Go To Channel`, but I guess we don't want to waste vertical spacing here.
- The commander field does not contain the avatar image.

A few more decisions worth pointing out:
- I am listing 10 incidents max. I did not add any way of requesting more, but I don't see the use case for being on your phone and browsing more than 10 incidents in this UI. If you think we should add that (or increase the 10 limit), please say so!
- I am rendering the same thing in mobile and webapp. The original goal was to list the incidents as an ephemeral message for mobile and let the webapp open the RHS. When we implement that feature, we can make the distinction.

| Mobile 	| Web 	|
|-:	|-:	|
|![image](https://user-images.githubusercontent.com/3924815/93781987-4bdfb700-fc2a-11ea-8ac3-fd8ee18537c2.png)|![image](https://user-images.githubusercontent.com/3924815/93782366-c7416880-fc2a-11ea-946e-5de42f999891.png)|

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28285

2020-09-21 16:00 UTC, asaadmahmood approved these changes

2020-09-21 16:16 UTC, lieut-data requested changes
Nice, pragmatic approach! A handful of comments, but not all blocking.

2020-09-21 16:16 UTC, lieut-data commented on server/bot/poster.go
> +func (b *Bot) EphemeralPost(userID, channelID string, post *model.Post) {
0/5, but at this point I'd be inclined to just use the API directly and abandon the bot interface.

2020-09-21 16:16 UTC, lieut-data commented on server/command/command.go
> +	options := incident.HeaderFilterOptions{
Will this list all incidents, or only incidents of which the current user is a part? @asaadmahmood, can you also confirm intent, noting that the only material difference would be public incidents.

2020-09-21 16:16 UTC, lieut-data commented on server/command/command.go
> +		r.postCommandResponse(fmt.Sprintf("Error retrieving the incidents: %v", err))
nit: This pattern seems to come up often. What about a `postCommandResponseError` to make things a bit more explicit?

2020-09-21 16:16 UTC, lieut-data commented on server/command/command.go
> +		r.postCommandResponse(fmt.Sprintf("Error retrieving the incidents: %v", err))
Actually, should we necessarily be posting the error details directly as a command response? For a non system-admin, this could theoretically leak too much info (i.e. "Postgres database down...")

2020-09-21 16:16 UTC, lieut-data commented on server/command/command.go
> +		duration := now.Sub(time.Unix(0, theIncident.CreateAt*1000000)).Round(time.Second)
Could we factor this out into a helper method that's possibly unit tested separately?

2020-09-21 16:16 UTC, lieut-data commented on server/command/command.go
> +		attachments[i] = &model.SlackAttachment{
Thoughts on separate posts vs. separate attachments? It might avoid the "long message" having to be expanded.

2020-09-21 16:16 UTC, lieut-data commented on server/command/command.go
> +			Text: fmt.Sprintf("### [%s](/%s/channels/%s)", channel.DisplayName, team.Name, channel.Name),
Is it possible to use a `~` reference instead? I think this might force a page refresh (not sure), but also has the problem of not handling subpaths (i.e. `/mattermost/<team_name>/channels/<channel name>`).

2020-09-21 19:54 UTC, cpoile requested changes
Nice work Alejandro! Some suggestions for the error reporting. Not sure Asaad and Tao want for the interface, but you could do paging if we need that.

2020-09-21 19:54 UTC, cpoile commented on server/command/command.go
> +		r.postCommandResponse(fmt.Sprintf("Error retrieving the incidents: %v", err))
Maybe: "Your request could not be completed. Check the system logs for more information." And then log the error with details.

If you made this a function, like `r.ReturnMsgAndLogError(err)`, then you can use it for all the errors below, too.

2020-09-21 19:54 UTC, cpoile commented on server/command/command.go
> +		PerPage: 10,
Re: your question about max 10 incidents in the response. It might be useful to offer a paged response, with a next and previous page link, like in the backstage incident list. What do you think @asaadmahmood, @itao ?

2020-09-21 19:54 UTC, cpoile commented on server/command/command.go
> +			r.postCommandResponse(fmt.Sprintf("Error retrieving playbook of incident '%s': %v", theIncident.Name, err))
Here for example: `r.ReturnMsgAndLogError(err)`

2020-09-22 11:34 UTC, agarciamontoro commented on server/bot/poster.go
> +func (b *Bot) EphemeralPost(userID, channelID string, post *model.Post) {
I think encapsulating the bot details is good, so I'd say we keep the interface. We can abandon it later if we see there's no need for it anymore.

2020-09-22 11:38 UTC, agarciamontoro commented on server/command/command.go
> +	options := incident.HeaderFilterOptions{
You're right! I added a `MembersIDs` field to the `HeaderFilterOptions` so we can filter by channel membership. I'd like you to take a look at the query here: https://github.com/mattermost/mattermost-plugin-incident-response/pull/291/commits/0a1b4c94837f9e821080d2918c873c524c792dfd

2020-09-22 11:57 UTC, agarciamontoro commented on server/command/command.go
> +		r.postCommandResponse(fmt.Sprintf("Error retrieving the incidents: %v", err))
I followed your suggestion, Christopher: https://github.com/mattermost/mattermost-plugin-incident-response/pull/291/commits/de7ddecdad787535f76a356ea4796db5710dcd2b

2020-09-22 11:57 UTC, agarciamontoro commented on server/command/command.go
> +		attachments[i] = &model.SlackAttachment{
I have a concern with the separate posts: as they are ephemeral, the user can dismiss them, so they may end up with what looks like a complete list that is, in fact, incomplete.

2020-09-22 12:07 UTC, agarciamontoro commented on server/command/command.go
> +			r.postCommandResponse(fmt.Sprintf("Error retrieving playbook of incident '%s': %v", theIncident.Name, err))
Done in https://github.com/mattermost/mattermost-plugin-incident-response/pull/291/commits/de7ddecdad787535f76a356ea4796db5710dcd2b

2020-09-22 12:38 UTC, lieut-data commented on server/command/command.go
> +		attachments[i] = &model.SlackAttachment{
Ah, good point!

2020-09-22 12:57 UTC, agarciamontoro commented
> I realize we validate the incoming member list as IDs, but this is only loosely connected to protecting ourselves against a SQL injection attack. In general, I'm extremely hesitant anytime we find ourselves needing to fmt.Sprintf and run SQL, and recommend always finding a way to avoid same.
In this particular case, I feel like filtering by MemberIDs in the plural might be overkil -- can we just filter by a particular MemberID instead and trivially bind that parameter? It seems unlikely that we need to support queries for incidents of which a set of users are members.

Makes sense! (It was fun to build that query, though)

2020-09-22 18:38 UTC, agarciamontoro commented on server/command/command.go
> +	options := incident.HeaderFilterOptions{
Ended up allowing filter by only one member. Done in https://github.com/mattermost/mattermost-plugin-incident-response/pull/291/commits/87317454e93487727be365779cc28208b7d62166.

2020-09-22 18:38 UTC, agarciamontoro commented on server/command/command.go
> +		duration := now.Sub(time.Unix(0, theIncident.CreateAt*1000000)).Round(time.Second)
Done in https://github.com/mattermost/mattermost-plugin-incident-response/pull/291/commits/529f972d6dc1985caa88e95c2440aa7b08d40547.

2020-09-22 20:13 UTC, agarciamontoro commented on server/command/command.go
> +			Text: fmt.Sprintf("### [%s](/%s/channels/%s)", channel.DisplayName, team.Name, channel.Name),
- `Title: fmt.Sprintf("~%s", channel.Name)` does not render as a link in mobile, but works on webapp.
- `Text: fmt.Sprintf("~%s", channel.Name)` ends up in Not Found in webapp, but works on mobile.
- `Pretext: fmt.Sprintf("~%s, channel.Name)` works on both, but does force a page refresh on webapp. This changes the styling a bit, but I do like the change.

I ended up using the latter. I took a real quick look at the webapp code parsing the attachments but saw nothing completely obvious. We can use the `Pretext` field and investigate the bug later.

Done in https://github.com/mattermost/mattermost-plugin-incident-response/pull/291/commits/1b25f2c639a3aa32c27324fbe92b02ee1a8b68d5.

2020-09-22 20:13 UTC, agarciamontoro commented on server/command/command.go
> +		PerPage: 10,
We decided to keep the maximum of 10 incidents in the meeting.

2020-09-22 20:15 UTC, agarciamontoro commented
Last commit changed a bit the styling. The options boxes are now preceded by the incident name with the link (that is now rendered with a tilde, so it may be more obvious that it is indeed a link to a channel):

![image](https://user-images.githubusercontent.com/3924815/93932849-136ed480-fd21-11ea-8347-016338ddc249.png)

2020-09-22 21:17 UTC, lieut-data approved these changes

2020-09-23 07:05 UTC, asaadmahmood approved these changes
I think the link in the header is fine for now, let us conduct some tests and see how users are interacting with this.

2020-09-24 12:06 UTC, agarciamontoro commented
I've added the `ActiveStageTitle` to the incident struct in https://github.com/mattermost/mattermost-plugin-incident-response/pull/291/commits/6ee4ea2ae151618cc34c7ae101a2d5b93099f0d9. I ended up needing to unmarshal the checklists for each incident in the `sqlStore.GetIncidents` method. But the return value is unchanged (except for the ActiveStageTitle, of course), as I am not adding the checklists to each individual incident (see `toIncidentWithoutChecklists`)
Please take a look, @lieut-data and @cpoile, thanks!

2020-09-24 12:47 UTC, lieut-data approved these changes
Nice!

2020-09-24 12:47 UTC, lieut-data commented on server/sqlstore/incident.go
> +			return nil, errors.Errorf("invalid ActiveStage in incident '%s': index is %d, but incident has %d checklists", rawIncident.ID, i.ActiveStage, len(i.Checklists))
Should we permanently fail to return the incident when this happens? Wondering if we just log a warning instead, and leave the title blank?

2020-09-24 13:36 UTC, agarciamontoro commented on server/sqlstore/incident.go
> +			return nil, errors.Errorf("invalid ActiveStage in incident '%s': index is %d, but incident has %d checklists", rawIncident.ID, i.ActiveStage, len(i.Checklists))
If this happens there's something completely wrong, so I'd say it's better to error as soon as possible.

2020-09-24 14:24 UTC, lieut-data approved these changes

2020-09-24 16:43 UTC, agarciamontoro commented
Waiting for v0.7.0 to be released before we merge this PR.

2020-09-25 16:12 UTC, agarciamontoro commented
Feel free to re-review when you have time, @cpoile, 0.7.0 is already tagged.

2020-09-28 14:19 UTC, cpoile requested changes
Nice work Alejandro! I have a concern about where we update the ActiveStage title. Otherwise, nicely done.

2020-09-28 14:19 UTC, cpoile commented on server/command/command.go
> +}
Nice!

2020-09-28 14:19 UTC, cpoile commented on server/command/command.go
> +	options := incident.HeaderFilterOptions{
This is good -- it's similar to something I did for the new RHS list, unfortunately. :) I'll have to deal with the merge later.

2020-09-28 14:19 UTC, cpoile commented on server/command/command_test.go
> +func TestDurationString(t *testing.T) {
Nice tests!

2020-09-28 14:19 UTC, cpoile commented on server/sqlstore/incident.go
> +			"CreateAt", "EndAt", "DeleteAt", "ActiveStage", "PostID", "PlaybookID", "ChecklistsJSON").
Is this supposed to be in here? I don't think we should retrieve `ChecklistsJSON` in the standard `incidentSelect`

2020-09-28 14:19 UTC, cpoile commented on server/sqlstore/incident.go
> +	if err := s.store.selectBuilder(s.store.db, &rawIncidents, queryForResults); err != nil {
Why do we need to include checklists in `GetIncidents`?

2020-09-28 14:19 UTC, cpoile commented on server/sqlstore/incident.go
> +	return &i, nil
I think we might be filling in the `ActiveStageTitle` in the wrong place. If we keep it updated whenever we create and update an incident, then it will be current. And we can go back to the way `GetIncidents` was before (with no unmarshaling of `ChecklistsJSON`). 

That will save a lot of processing Checklists (since we call `GetIncidents` often, but we only need the active stage for the Incident List command).

2020-09-28 14:22 UTC, agarciamontoro commented on server/command/command.go
> +}
Thanks!

2020-09-28 14:22 UTC, agarciamontoro commented on server/command/command_test.go
> +func TestDurationString(t *testing.T) {
:tada:

2020-09-28 14:27 UTC, agarciamontoro commented on server/sqlstore/incident.go
> +	if err := s.store.selectBuilder(s.store.db, &rawIncidents, queryForResults); err != nil {
@cpoile How else could we retrieve the active stage title if we don't have the checklists? Or was your suggestion adding a new column to the incident table?

2020-09-28 18:15 UTC, agarciamontoro commented on server/sqlstore/migrations.go
> +			}
I decided to do an update per incident for two reasons:
- building an update for multiple rows it's different for postgresql and mysql, and I did not find it as straightforward as it should be in any of them
- the number of incidents any server can have at this point is still low, so I don't see there's any performance concern.

2020-09-28 18:17 UTC, agarciamontoro commented
After an offline conversation with @cpoile I solved my misunderstanding, as I was not aware that the proposal was to add a new column to the database! My last commit changes the implementation of the `ActiveStageTitle` field in order to move it inside the `IR_Incident` table, as it was first intended. Christopher, please, take a look into it and see if I missed something :)

2020-09-28 21:26 UTC, lieut-data approved these changes

2020-09-28 21:26 UTC, lieut-data commented on server/sqlstore/migrations.go
> +					return errors.Errorf("index %d out of bounds: incident %s has %d stages", theIncident.ActiveStage, theIncident.ID, numChecklists)
nit: /if/ this every fails, the plugin is dead in the water, requiring an upgrade to run the new version. Should we just fall back to an empty string here, with a warning?

2020-09-29 07:55 UTC, agarciamontoro commented on server/sqlstore/migrations.go
> +					return errors.Errorf("index %d out of bounds: incident %s has %d stages", theIncident.ActiveStage, theIncident.ID, numChecklists)
Good catch! Done in https://github.com/mattermost/mattermost-plugin-incident-response/pull/291/commits/cd28c42487068430ced220c8f5c80444412a99ac.

2020-09-29 12:36 UTC, lieut-data approved these changes

2020-09-29 21:58 UTC, cpoile requested changes
Nice!

2020-09-29 21:58 UTC, cpoile commented on server/sqlstore/incident.go
> +		From("IR_Incident")
I don't think you need to add the `From` clause (it's in the `s.incidentSelect`), and if we do this I'm worried we'll lose the `AS incident` naming (if it's needed -- I can't remember).

2020-09-29 21:58 UTC, cpoile commented on server/sqlstore/incident.go
> +
I /think/ we might be able to do this simpler in `incident/service.go` line 515 -- set the active stage title when we change the active stage. Then we don't have to have the `syncActiveStageTitle` method, and we don't have to do bounds checking (it's done already in the `ChangeActiveStage` method). I'm prettttttty sure that's the only place it's possible to change the active stage, can you double check? (If you can set it directly through the API, then maybe this is better.) Let me know what you think is better and we'll go with that.

2020-09-30 07:26 UTC, agarciamontoro commented on server/sqlstore/incident.go
> +		From("IR_Incident")
Hm, I just brought back what was there, I'll test whether we need it or not, but it looks like we don't.

2020-09-30 07:35 UTC, agarciamontoro commented on server/sqlstore/incident.go
> +
I spent a bit of time trying to decide where to put this, and decided to do it here to be as close to the real data as possible. I'm afraid we call this method directly, wanting it to sync, and later discovering it does not. But I like the fact that we don't need to do bounds checking (it's a bit annoying) so I'll move it to the service and be explicit on the documentation. I'm also pretty sure it's the only place, I double checked, but I'll triple check!
We can do it directly through the API, but we would need to repeat the bounds checking, then. I think the service is the least evil option.

2020-09-30 08:38 UTC, agarciamontoro commented on server/sqlstore/incident.go
> +		From("IR_Incident")
You were right, if we leave the `From` clause, it removes the `AS incident` part. The alias is not needed here, but neither is this additional line. Removed in https://github.com/mattermost/mattermost-plugin-incident-response/pull/291/commits/9b69d5881c74bdee8614908098d369776c0de28b.

2020-09-30 08:39 UTC, agarciamontoro commented on server/sqlstore/incident.go
> +
Moved all syncing to the service (it turns out I had already added it to `ChangeActiveStage`, too). See https://github.com/mattermost/mattermost-plugin-incident-response/pull/291/commits/b63da87497657f664cb83d47ad2c55b1f89adeb5.

2020-09-30 12:34 UTC, lieut-data approved these changes

2020-09-30 12:42 UTC, cpoile approved these changes
Awesome! Thanks @agarciamontoro, apologies for the churn!

2020-09-30 12:42 UTC, merged

2020-09-30 12:58 UTC, agarciamontoro commented
> Apologies for the churn!

No problem at all! Thank you for a thorough awesome review :)