/incident commander
mattermost/mattermost-plugin-incident-response pull request #293
Opened 2020-09-23 15:34 UTC by lieut-data

#### Summary
Support `/incident commander` to show the current commander:
<img width="353" alt="image" src="https://user-images.githubusercontent.com/1023171/94034795-ca5a6700-fd98-11ea-8929-deb903f08142.png">

and `/incident commander @username` to change it:
<img width="461" alt="image" src="https://user-images.githubusercontent.com/1023171/94035061-10afc600-fd99-11ea-8398-a73b77a8727f.png">

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-28287
Relates-to: https://github.com/mattermost/mattermost-plugin-api/pull/75

2020-09-23 15:36 UTC, lieut-data commented on go.mod
> +	github.com/mattermost/mattermost-plugin-api v0.0.12-0.20200923151715-5a2508c31e48
This is related to https://github.com/mattermost/mattermost-plugin-api/pull/75.

2020-09-23 15:36 UTC, lieut-data commented on server/command/command.go
> +		r.postCommandResponse(fmt.Sprintf("Error retrieving incident: %v", err))
I'll probably leverage your changes, @agarciamontoro, to not expose errors directly, resolving merge conflicts along the way.

2020-09-23 15:36 UTC, lieut-data commented on tests-e2e/cypress/fixtures/theme.json
> +{
Copying stuff from the webapp.

2020-09-24 21:51 UTC, cpoile approved these changes

2020-09-24 21:51 UTC, cpoile commented on server/command/command.go
> +	targetCommanderUsername := strings.TrimLeft(args[0], "@")
Are all leading and trailing whitespace removed before sending arguments?

2020-09-24 21:51 UTC, cpoile commented on server/command/command.go
> +	currentIncident.CommanderUserID = targetCommanderUser.Id
Is this needed?

2020-09-24 21:51 UTC, cpoile commented on tests-e2e/cypress/integration/frontstage/slash_command_spec.js
> +    describe('/incident commander', () => {
awesome tests!

2020-09-25 12:43 UTC, agarciamontoro requested changes
Nice!!! I'll copy these tests to `/incident info`!

I left some suggestions below

2020-09-25 12:43 UTC, agarciamontoro commented on server/command/command.go
> +	commander.AddTextArgument("The desired commander.", "[@username]", "")
Can we be super explicit here? Having the same command to show current commander and to set a new one can be a bit dangerous. Maybe we can just say "The desired new commander." Otherwise, I can think of the command `/incident commander @user` as a way of showing info of the commander `@user`

2020-09-25 12:43 UTC, agarciamontoro commented on server/command/command.go
> +		r.postCommandResponse(helpText)
nit: is it possible to prepend a specific error here for informing the user what happened? Something like "`/incident commander` expects one argument at most`? Maybe this is not how it is handled elsewhere, but I think this command UI should be polished for being useful.

2020-09-25 12:43 UTC, agarciamontoro commented on server/command/command.go
> +	r.postCommandResponse(fmt.Sprintf("**@%s** is the current commander for **%s**", commanderUser.Username, currentIncident.Name))
I've seen this formatting misbehave when implementing `/incident list`: as the incident name may have trailing spaces, we may end up with the asterisks in the text itself, which will be no longer bold. Can we trim `currentIncident.Name` here to make sure the format is ok?

2020-09-25 12:43 UTC, agarciamontoro commented on server/command/command.go
> +		r.postCommandResponse("This is not an incident channel.")
Nit: this kind of error (also repeated in `actionChangeCommander`) is shown elsewhere as:
- `You can only check/uncheck an item from within the incident's channel`
- `You can only announce from within the incident's channel.`
- `You can only end an incident from within the incident's channel.`
- `You can only restart an incident from within the incident's channel.`

Maybe we should stick to that format (or change all others to this one) for the sake of consistency.

2020-09-25 12:43 UTC, agarciamontoro commented on tests-e2e/cypress/integration/frontstage/slash_command_spec.js
> +    describe('/incident commander', () => {
agree!

2020-09-25 12:43 UTC, agarciamontoro commented on tests-e2e/cypress/integration/frontstage/slash_command_spec.js
> +        describe('should show an message when the user is already the commander', () => {
Typo:
```suggestion
        describe('should show a message when the user is already the commander', () => {
```

2020-09-25 13:44 UTC, lieut-data commented on server/command/command.go
> +	currentIncident.CommanderUserID = targetCommanderUser.Id
Nope! Vestigial from when I thought I had to `UpdateIncident` to effect a commander change. Thanks :)
```suggestion
```

2020-09-25 13:56 UTC, lieut-data commented on server/command/command.go
> +	targetCommanderUsername := strings.TrimLeft(args[0], "@")
Indeed -- `args` here effectively comes from `strings.Fields` on the incoming slash command string, which handles this natively.

2020-09-25 13:57 UTC, lieut-data commented on server/command/command.go
> +	r.postCommandResponse(fmt.Sprintf("**@%s** is the current commander for **%s**", commanderUser.Username, currentIncident.Name))
Good catch! Stripping markdown here.

2020-09-25 14:00 UTC, lieut-data commented on server/command/command.go
> +	r.postCommandResponse(fmt.Sprintf("**@%s** is the current commander for **%s**", commanderUser.Username, currentIncident.Name))
Actually, it's probably easier just to say `this incident` here like the other error messages.

2020-09-25 14:02 UTC, lieut-data commented on server/command/command.go
> +		r.postCommandResponse("This is not an incident channel.")
Excellent!

2020-09-25 14:07 UTC, lieut-data commented on server/command/command.go
> +		r.postCommandResponse(helpText)
I like this much better -- but going to just show that message vs. prepending to the whole help text. Hopefully that's enough?

2020-09-25 14:32 UTC, agarciamontoro commented on server/command/command.go
> +		r.postCommandResponse(helpText)
Yeah, I think the valuable part here is the specific message.

2020-09-25 14:55 UTC, agarciamontoro approved these changes
:tada:

2020-09-30 18:07 UTC, lieut-data commented
I'm going to force merge this on the belief that the linting error above is bogus. If not, I'll keep iterating.

2020-09-30 18:07 UTC, merged