MM-29009 - Allow playbooks and incident stages with no checklists
mattermost/mattermost-plugin-incident-response pull request #297
Opened 2020-09-24 21:03 UTC by cpoile

#### Summary
- This was a bit more tricky than just removing the error. We are expecting there to always be checklists in the frontend. I cleared up the errors, so things work, but the backstage incident details checklist graph doesn't render if there are no items in the first checklist. I recommend splitting that off into another ticket. There might be other affects of this change. 
- I'm not sure this should go in last minute for 0.7.0, considering the possible unanticipated effects...
- I also fixed a bug where if the incident being sent over websockets didn't fit the typescript definition of an incident (e.g., there was a null instead of an array --- that again) the websocket event wouldn't be passed on and the frontend wouldn't update. So you can click a checkbox and nothing in the UI would change (but you would see the 'checklist item has been checked' message in the centre channel).

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-29009

2020-09-24 21:34 UTC, crspeller requested changes

2020-09-24 21:34 UTC, crspeller commented on webapp/src/websocket_events.ts
> +            incident = removeNulls(incident);
What if it's still not an incident?

2020-09-24 21:34 UTC, crspeller commented on server/api/incidents.go
> +func removeNulls(theIncident *incident.Incident) {
I wonder if it would be cleaner, instead of doing this here, to use a custom `MarshalJSON` for the incident and playbook types that does this.

2020-09-24 21:40 UTC, cpoile commented on webapp/src/websocket_events.ts
> +            incident = removeNulls(incident);
I'm not sure when that would happen -- unless we're sending bad data to the client? Either way, I don't think this `isIncident` thing does what it's supposed to do. It's supposed to help Typescript know what the object really is, so it can use that later. But it doesn't seem to do that for me. Does it do anything for you? For now I'm using it as `check that the arrays aren't null`.

2020-09-24 21:41 UTC, cpoile commented on server/api/incidents.go
> +func removeNulls(theIncident *incident.Incident) {
Maybe, but would that effort be worth it?

2020-09-25 13:07 UTC, cpoile commented on server/api/incidents.go
> +func removeNulls(theIncident *incident.Incident) {
I thought about it overnight, and you're right -- I'll wright a MarshalJSON and that will eliminate the need for the screwy checks and changes in the frontend. Thanks!

2020-09-25 13:52 UTC, cpoile commented on webapp/src/websocket_events.ts
> +            incident = removeNulls(incident);
I decided to log an error to the console. This shouldn't happen, so if it does we should know about it and fix it (it probably means we're sending bad data from the backend).

2020-09-25 14:21 UTC, cpoile commented
Fixed the checklist timeline in the backstage. I've poked around, and I think everything works as expected now. 
Will need Prapti to do another smoke test to make sure there aren't any other side effects from allowing this change.

2020-09-25 14:36 UTC, crspeller commented on server/api/incidents.go
> +func removeNulls(theIncident *incident.Incident) {
Awesome 😄

2020-09-25 14:36 UTC, crspeller approved these changes
Looks good!

2020-09-28 16:38 UTC, lieut-data approved these changes
Really slick!

2020-09-28 16:38 UTC, merged