Adding playbook backstage tests
mattermost/mattermost-plugin-incident-response pull request #305
Opened 2020-09-30 00:50 UTC by prapti

Adding a couple of more playbook backstage test with plans to add more tests as we go:
* backstage_spec:
    * Verifying that backstage opens playbook creation page with New Playbook button.
    * Verifying that backstage opens playbook creation page with "Blank Playbook" template option
    * Verifying that backstage opens Incident Response Playbook page from its template option
* playbook_details_spec:
    * Backstage playbook details has the page specific UI components

Screenshots:
![Screen Shot 2020-09-29 at 5 43 20 PM](https://user-images.githubusercontent.com/691331/94631037-37c83500-027c-11eb-9cee-c6b307711ec0.png)
![Screen Shot 2020-09-29 at 5 47 49 PM](https://user-images.githubusercontent.com/691331/94631042-3bf45280-027c-11eb-838d-8b087ec84deb.png)

2020-10-01 12:52 UTC, lieut-data requested changes
Thanks, @prapti! A few comments below.

2020-10-01 12:52 UTC, lieut-data commented on tests-e2e/cypress/integration/backstage/backstage_spec.js
> +    it('opens playbook creation page with New Playbook button', () => {
nit: missing newline separating tests
```suggestion

     it('opens playbook creation page with New Playbook button', () => { 
```

2020-10-01 12:52 UTC, lieut-data commented on tests-e2e/cypress/integration/backstage/backstage_spec.js
> +    it('opens playbook creation page with New Playbook button', () => {
Related, this test feels like it belongs in the `playbook_list_spec.js`? I had imagined the vanilla `backstage_spec.js` was more about the shared elements, like the navigation header.

2020-10-01 12:52 UTC, lieut-data commented on tests-e2e/cypress/integration/backstage/backstage_spec.js
> +function verifyPlaybookCreationPageOpened(template=false) {
What does the `template` parameter do?

2020-10-01 12:52 UTC, lieut-data commented on tests-e2e/cypress/integration/backstage/backstage_spec.js
> +        // * Verify the page url contains 'Incident Response Playbook'
Can we find a way to use `verifyPlaybookCreationPageOpened`?

2020-10-01 12:52 UTC, lieut-data commented on tests-e2e/cypress/integration/backstage/playbook_details_spec.js
> +    it('has playbook specific UI components', () => {
I'm not a fan of this test, specifically -- it seems brittle as compared to a test focusing on /doing/ something, like creating a playbook using these specific UI components.

2020-10-03 00:55 UTC, prapti commented on tests-e2e/cypress/integration/backstage/playbook_details_spec.js
> +    it('has playbook specific UI components', () => {
I didn't have a very strong feeling about adding a "UI component test" either.. getting rid of it :)

2020-10-03 00:57 UTC, prapti commented on tests-e2e/cypress/integration/backstage/backstage_spec.js
> +function verifyPlaybookCreationPageOpened(template=false) {
Nothing in this case, it was a bad cleanup on my part. Updated this function for better use.

2020-10-03 00:59 UTC, prapti commented on tests-e2e/cypress/integration/backstage/backstage_spec.js
> +    it('opens playbook creation page with New Playbook button', () => {
I agree that it does not quite fit in the `backstage_spec`. Maybe I'll move it to a `playbook_creation_spec`.

2020-10-04 00:08 UTC, lieut-data approved these changes
Momentum! Yee haw -- thanks, @prapti :)

2020-10-06 02:45 UTC, prapti commented
/update-branch

2020-10-07 21:57 UTC, merged