MM-29136 - Fix backstage jump to channel
mattermost/mattermost-plugin-incident-response pull request #308
Opened 2020-10-01 14:53 UTC by cpoile

#### Summary
- The bug was caused by our new MarshalJSON being called on an `incident.Details` struct, but only the embedded `incident.Incident` was being marhaled. I tried creating a MarshalJSON for incident.Details, but it kept calling the embedded incident.Incident's marshaller. Looks like this might be a bug in Go itself: https://github.com/golang/go/issues/31167 
- I worked around it by separating the embedded structs, calling each and splicing them together to create the full json. I think this is what we have to do, or else make a whole new struct for the details (not do the embedding) as Christopher suggested. In the end, this is what a marshaler does (byte slice manipulation), so it doesn't feel too hacky. Depends on what you guys think after seeing the code.
- This was not found by the api tests for get details... because the tests were wrong. Sorry about that. Tests are fixed now.

#### Retrospective
- This would have been caught if we were doing type guarding and surfacing the mismatches correct in the front end, but that had gone out of sync, and we were just casting raw json into the types we /thought/ we were getting from the backend.
- And in the backstage details we were casting an empty object into an `Incident`, so I don't know how any of that passed the type checker. We should probably go through and make sure types really are that type, and use the union null  to be explicit that the object might not be there.
- This PR fixes the problem for incident details, but it doesn't fix all the other similar problems we have in the frontend.
- I think we should chat about this in the Monday meeting, because it will be a bit of work, and will be work to maintain equivalence between the backend/frontend. I'd love opinions on cost/benefit of doing this for every type coming from the backend. 

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-29136

2020-10-01 15:58 UTC, cpoile commented
/update-branch

2020-10-01 16:03 UTC, lieut-data requested changes
Thanks, @cpoile! A couple of comments below (which might be stale, since I think I'm reviewing a slightly older set of changes with this review).

2020-10-01 16:03 UTC, lieut-data commented on webapp/src/client.ts
> +    if (!isIncidentWithDetails(data)) {
I'm not convinced we want this in production code. Can we find a way to run this only for development?

2020-10-01 16:03 UTC, lieut-data commented on webapp/src/components/backstage/incidents/incident_details/incident_details.tsx
> +    if (fetchingState === FetchingStateType.notFound || incident === null) {
Won't `incident` always be `null` when the component first renders, resulting in an unconditional `Redirect` before we have a chance to load the incident?

2020-10-01 16:03 UTC, lieut-data commented on webapp/src/types/incident.ts
> +export interface IncidentWithDetails extends Incident {
Hmm, I was expecting to see an object with fields `incident` and `details`, thus matching the backend type. Actually, this would eliminate the need to do the special `MarshalJSON` handling altogether. Thoughts?

2020-10-01 16:13 UTC, cpoile commented on webapp/src/types/incident.ts
> +export interface IncidentWithDetails extends Incident {
Sorry, I don't know how it would prevent the need for the MarshalJSON, can you clarify?

2020-10-01 16:13 UTC, cpoile commented on webapp/src/components/backstage/incidents/incident_details/incident_details.tsx
> +    if (fetchingState === FetchingStateType.notFound || incident === null) {
That will be caught by the conditional above `if (fetchingState === FetchingStateType.loading)`.

2020-10-01 17:35 UTC, lieut-data commented on webapp/src/types/incident.ts
> +export interface IncidentWithDetails extends Incident {
I'd presume we'd just send down `{incident: {...}, details: {...}}`.

2020-10-01 17:36 UTC, cpoile commented on webapp/src/types/incident.ts
> +export interface IncidentWithDetails extends Incident {
Oh, the structure of what's sent down is fine--it's flat. We're doing the custom MarshalJSON to convert nil slices into empty slices.

2020-10-01 19:01 UTC, cpoile commented on server/incident/incident.go
> +	combinedJSON := make([]byte, 0, len(incidentJSON)+len(detailsJSON)-1)
Yep, it's nicer. Been awhile since I've used it, forgot about it. Thanks!

2020-10-01 19:03 UTC, cpoile commented on webapp/src/client.ts
> +    if (!isIncidentWithDetails(data)) {
I'm using the client config from redux, but calling it the SystemSettings (since that's what it is--Harrison says it's misnamed anyway). I'm putting it in its own module so that we can get that info from non-react components (like the functions in client).

2020-10-01 19:06 UTC, cpoile commented on webapp/src/types/incident.ts
> +export interface IncidentWithDetails extends Incident {
Oh, no I see what you mean now...  Let me check that.

2020-10-01 19:20 UTC, cpoile commented on webapp/src/types/incident.ts
> +export interface IncidentWithDetails extends Incident {
Yep, it works. It leads to stuttering in the backstage details, but we can fix that if we want by calling `incident` something else.

2020-10-01 19:33 UTC, lieut-data requested changes
A bit of a mouthful, but seems slightly cleaner. A few thoughts on the developer mode below.

2020-10-01 19:33 UTC, lieut-data commented on webapp/src/client.ts
> +    if (SystemSettings.EnableDeveloperMode && !isIncident(data)) {
Actually, instead of tying this to a server setting, can we just have webpack compile this out for production builds, that way everything is tied together with the same "concept" vs. having something else to enable to get testing? See the following for an example:

https://github.com/mattermost/mattermost-webapp/blob/f8e7fc90a138c1c7ea6e018fb7426de4104273d8/stores/redux_store.jsx#L17-L19

2020-10-01 19:33 UTC, lieut-data commented on webapp/package.json
> +    "build:watch": "webpack --mode=development --watch",
Can we avoid changing this, and just rely on the developer running with `MM_DEBUG` instead? Otherwise we'll want to surface this back to the starter-template, etc.

2020-10-01 19:33 UTC, lieut-data commented on webapp/src/components/backstage/incidents/incident_details/incident_details.tsx
> +        navigateToUrl(`/${incident.details.team_name}/channels/${incident.details.channel_name}`);
Maybe we call it `incidentWithDetails.details` to make `incident.incident.*` a bit less of a mouthful?

2020-10-01 19:34 UTC, cpoile commented on webapp/src/client.ts
> +    if (SystemSettings.EnableDeveloperMode && !isIncident(data)) {
I thought about that, except that a lot of developers use `make deploy` to deploy the plugin while developing, right? And then the environment would be production... What do you think?

2020-10-01 19:36 UTC, cpoile commented on webapp/package.json
> +    "build:watch": "webpack --mode=development --watch",
It's so weird that `build:watch` is production mode, isn't it? That's what I use for development all the time (along with `make deploy`, actually). Is there a reason this is set to production?

2020-10-01 19:37 UTC, cpoile commented on webapp/src/components/backstage/incidents/incident_details/incident_details.tsx
> +        navigateToUrl(`/${incident.details.team_name}/channels/${incident.details.channel_name}`);
It's the stutter vs more typing, I guess.  🤷

2020-10-01 20:38 UTC, cpoile commented on webapp/package.json
> +    "build:watch": "webpack --mode=development --watch",
I reverted these changes -- we can discuss and do a wholesale change to the starter template later

2020-10-01 20:39 UTC, cpoile commented on webapp/src/components/backstage/incidents/incident_details/incident_details.tsx
> +        navigateToUrl(`/${incident.details.team_name}/channels/${incident.details.channel_name}`);
I made the change, I do think it's better without the stutter: less confusing

2020-10-01 20:44 UTC, cpoile commented on webapp/src/client.ts
> +    if (SystemSettings.EnableDeveloperMode && !isIncident(data)) {
After thinking about it, I vote for keeping it pegged to the server's mode. Basically my reasoning is: we don't know what the npm mode is because of the weird way we set production and developer flag below, and the many different ways a developer could be sending a plugin to the server. So, we don't know if a developer will have the npm developer flag on. But these errors need attention, so we want to make sure every developer sees them.

2020-10-01 21:13 UTC, lieut-data commented on webapp/src/client.ts
> +    if (SystemSettings.EnableDeveloperMode && !isIncident(data)) {
If `MM_DEBUG` is set (or `DEBUG` as currently in incident response until we update from the starter-template), then `make deploy ` and `make watch` will both generate debug builds suitable for developers, including unmified code, debugging symbols, etc. 

Is there a use-case for getting debugging statements like this from a minified production build being used for development?

2020-10-01 21:20 UTC, cpoile commented on webapp/src/client.ts
> +    if (SystemSettings.EnableDeveloperMode && !isIncident(data)) {
To be honest, I didn't know about `MM_DEBUG` or `DEBUG`... But, I just tried it, and setting it style compiles the webapp with `mode=none`.  So those errors would not be surfaced if you run `DEBUG=true make deploy` or `make debug`.  Is that okay? (I feel like I might be missing something, since it seems like we should be erring (hah) on the side of outputting these errors on everything except a production server, no?)

2020-10-02 03:06 UTC, lieut-data commented on webapp/package.json
> +    "build:watch": "webpack --mode=development --watch",
I admit to having done this intentionally, primarily so that the `MM_DEBUG` semantics were consistently applied, vs. being "special" depending on some contexts. But I do think there is a rationale for `build:watch` in production mode, simply because there is a non-trivial performance difference, and it can be useful to develop in production mode and only jump into development mode if issues arise that require further debugging. At least, that's how I usually develop.

We could certainly raise the visibility of `MM_DEBUG` when doing development, though!

2020-10-02 03:09 UTC, lieut-data commented on webapp/src/client.ts
> +    if (SystemSettings.EnableDeveloperMode && !isIncident(data)) {
Ah, interesting. `mode=none` does indeed sound like the wrong choice, and maybe we need to explicitly go for `mode=development` to get the desired behaviour.

2020-10-02 10:24 UTC, agarciamontoro reviewed
Great catch, Chris, this was not a simple bug! I like the solution for the specific bug, but I agree that we should talk on Monday about how to handle this holistically from now on.

2020-10-02 13:31 UTC, cpoile commented on webapp/src/client.ts
> +    return data as Incident;
@agarciamontoro That's an interesting solution. I was about to say: Surface an error but return a <Incident | null>. But then I realize that we don't actually want to set a non-conforming JSON object from the server to `null`, do we? That would break everything if just one field was missing. Or is that what we want to do?

2020-10-02 18:55 UTC, cpoile commented on webapp/src/client.ts
> +    return data as Incident;
After the discussion in the channel, it makes more sense to cast and pass it along, after doing a development-only type guard.

2020-10-02 18:56 UTC, cpoile commented on webapp/src/index.tsx
> +
not needed now, but yes that would have been necessary, thanks!

2020-10-02 18:56 UTC, cpoile commented on webapp/package.json
> +    "build:watch": "webpack --mode=development --watch",
After discussion offline, making one small change here.

2020-10-02 18:56 UTC, cpoile commented on webapp/src/client.ts
> +    if (SystemSettings.EnableDeveloperMode && !isIncident(data)) {
As discussed offline, going to `mode=development` makes the most sense, and using `process.env.NODE_ENV` is most desirable because webpack will tree-shake it out.

2020-10-02 19:06 UTC, lieut-data approved these changes
:tada:

2020-10-02 19:16 UTC, merged