MM-28607: run slash command polish
mattermost/mattermost-plugin-incident-response pull request #310
Opened 2020-10-01 21:50 UTC by lieut-data

#### Summary
Track when the last slash command was successfully run, and use that to show `Rerun` instead of just `Run`.

A bit of visual polish:
<img width="161" alt="image" src="https://user-images.githubusercontent.com/1023171/94867046-d092b800-0416-11eb-8b62-d7b2a1f3c903.png">

Oh, and I eliminated the spinners in most of the weird places we used them before because they just glitch right now. We can revisit that holistically later.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28607

2020-10-02 10:48 UTC, agarciamontoro requested changes
A much nicer look. And thank you for removing the spinners, agree that the blinking was not a good experience.

2020-10-02 10:48 UTC, agarciamontoro commented on webapp/src/components/checklist_item.tsx
> +    if (props.checklistItem.command_last_run && lastRun && props.checklistItem.command_last_run > lastRun) {
nit: do we need the first two conditionals here? The last condition will fail in case they are both 0, which I understand is their default value.

2020-10-02 10:48 UTC, agarciamontoro commented on webapp/src/components/checklist_item.tsx
> +                        {props.checklistItem.command_last_run ? 'Rerun' : 'Run'}
Actually, do we need the state of `lastRun, setLastRun`? Can't we just use this field of the prop? If it changes, it will re-render, isn't it?

2020-10-02 10:48 UTC, agarciamontoro commented on webapp/src/types/playbook.ts
> +    command_last_run?: number;
Does this need to be optional? We can check for its zero value.

2020-10-02 10:48 UTC, agarciamontoro commented on webapp/src/types/playbook.ts
> +    command_last_run?: number;
Also, we may need to add this new field to the `isChecklistItem` function at the end of this file.

2020-10-02 12:20 UTC, lieut-data commented on webapp/src/components/checklist_item.tsx
> +    if (props.checklistItem.command_last_run && lastRun && props.checklistItem.command_last_run > lastRun) {
Indeed, I [wrestled](https://community-daily.mattermost.com/core/pl/3u3xwpkhzbnypcw5g56kw97p9a) with this for a bit before giving up and letting TypeScript win. Since both are optional, they might be null.

2020-10-02 12:22 UTC, lieut-data commented on webapp/src/components/checklist_item.tsx
> +                        {props.checklistItem.command_last_run ? 'Rerun' : 'Run'}
The `lastRun`/`setLastRun` is mostly to force the spinner off as soon as we hear back from the server (allowing me to sense the delta, as opposed to just using the current value). Otherwise, the text re-renders to `Rerun` while the spinner is still showing, which felt weird somehow. But maybe I'm overthinking this, and that behaviour is just fine?

2020-10-02 12:23 UTC, lieut-data commented on webapp/src/types/playbook.ts
> +    command_last_run?: number;
It's only optional because otherwise I have to litter parts of the code with `command_last_run: 0` when creating a playbook before sending it up to the server. Good catch on `isChecklistItem` -- I didn't realize this existed :)

2020-10-02 13:25 UTC, agarciamontoro commented on webapp/src/components/checklist_item.tsx
> +                        {props.checklistItem.command_last_run ? 'Rerun' : 'Run'}
Ah ok ok, it makes sense. Agree to have the state, then, I had not thought about that case!

2020-10-02 15:24 UTC, lieut-data commented on webapp/src/types/playbook.ts
> +    command_last_run?: number;
Moved to making `command_last_run` not optional. Thoughts?

2020-10-02 15:46 UTC, agarciamontoro approved these changes
Yay! I think that's much better, thank you! :tada:

2020-10-04 14:36 UTC, cpoile approved these changes

2020-10-04 14:36 UTC, cpoile commented on webapp/src/components/checklist_item.tsx
> +                        {props.checklistItem.command_last_run ? 'Rerun' : 'Run'}
This looks great, thanks Jesse!

2020-10-05 12:57 UTC, merged