Create .gitbook.yaml
mattermost/mattermost-plugin-incident-response pull request #313
Opened 2020-10-05 17:33 UTC by justinegeffen

Added file for Gitbook docs.

2020-10-05 17:57 UTC, lieut-data approved these changes

2020-10-06 14:16 UTC, lieut-data commented
@justinegeffen, I'm guessing this is a work in progress? I've marked it using the label and removed myself and @crspeller as reviewers -- feel free to ping whenever you think it's good to go :)

2020-10-06 14:18 UTC, justinegeffen commented
Thanks, @lieut-data. I'd initially wanted to just add the Gitbook docs directory but decided to populate it with content at the same time. I'll re-add you when it's all good to go, which should be later today. :)

2020-10-07 13:42 UTC, lieut-data approved these changes
This is great -- still some missing parts, but let's just keep iterating. A few comments below, but not blocking.

2020-10-07 13:42 UTC, lieut-data commented on docs/glossary.md
> +* **Active incident:** An incident that has not been ended.
It feels weird to define `Active incident`, when the terminology in-app is `Ongoing incident`. Should we just skip this one?
```suggestion
```

2020-10-07 13:42 UTC, lieut-data commented on docs/incidents/ending-an-incident.md
> +The owner of the incident can end it via either a slash command or the right-hand sidebar.
Propose adding something akin to:

> Ending an incident signals to all participants that the issue has been resolved. Some playbooks may define stages and tasks to complete after an incident has been resolved, such as scheduling and completing a post-mortem. The incident RHS remains fully accessible even after an incident has ended.

2020-10-07 13:42 UTC, lieut-data commented on docs/incidents/managing-an-incident.md
> +- Mark a step as in progress or completed
It's no longer possible to model `In progress` -- it's either incomplete, or completed (as seen by the state of the checkbox).

2020-10-07 13:42 UTC, lieut-data commented on docs/playbooks/incident-task-management.md
> +You can plan your incident response workflow in advance using steps and stages to allocate tasks to team members who'll form part of the incident.
nit: `who'll` doesn't sound right to my ears -- should we prefer `who will` in this context?

2020-10-07 13:45 UTC, justinegeffen commented on docs/playbooks/incident-task-management.md
> +You can plan your incident response workflow in advance using steps and stages to allocate tasks to team members who'll form part of the incident.
Yeah, I'm happy with that. It does look/sound a bit jarring.

2020-10-07 13:46 UTC, lieut-data commented
Oops! Sorry for the early review, @justinegeffen :D

2020-10-07 13:47 UTC, justinegeffen commented
I should be the one apologizing for not letting you know I'd rescinded the request. :) You were too quick for me! :D

2020-10-07 17:57 UTC, justinegeffen commented on docs/incidents/ending-an-incident.md
> +The owner of the incident can end it via either a slash command or the right-hand sidebar.
That's perfect, thank you!

2020-10-07 17:57 UTC, justinegeffen commented on docs/playbooks/incident-task-management.md
> +You can plan your incident response workflow in advance using steps and stages to allocate tasks to team members who'll form part of the incident.
```suggestion
You can plan your incident response workflow in advance using steps and stages to allocate tasks to team members who will form part of the incident. 
```

2020-10-07 20:03 UTC, justinegeffen commented
@itao, @agarciamontoro, @lieut-data: This is still WIP but I'd like it to be merged so the content is published and I can iterate on it. 

@agarciamontoro, would you be open to me folding some of your README content into this so there's no duplication? It'll be in a separate PR once this one is out.

2020-10-08 09:02 UTC, agarciamontoro commented
> @agarciamontoro, would you be open to me folding some of your README content into this so there's no duplication? It'll be in a separate PR once this one is out.

@justinegeffen, absolutely! I'll review this as soon as possible.

2020-10-08 13:35 UTC, agarciamontoro requested changes
This is great, thank you @justinegeffen! :tada: 

I left some comments below, mostly nits. I did not render the files locally, so I don't know if there's any formatting issue. I'll try to take a look at that later.

2020-10-08 13:35 UTC, agarciamontoro commented on docs/administrator-guide/permissions.md
> +Only members of the team in which the playbook or incident is defined have access. Additionally, membership of playbook is independent of membership in incidents:
Is it "membership *of* incidents" here? Not sure at all, but I noticed it's different from "membership of playbook".

2020-10-08 13:35 UTC, agarciamontoro commented on docs/administrator-guide/permissions.md
> +- Members of a playbook may start an incident using that playbook, or edit the playbook's stages and steps.
Nit: in a first read, this looked like they can do either of those things, but not both.
```suggestion
- Members of a playbook may start an incident using that playbook, and edit the playbook's stages and steps.
```

2020-10-08 13:35 UTC, agarciamontoro commented on docs/glossary.md
> +* **Playbook:** A set of steps to execute as part of resolving an incident. It consists of one or more checklists, with each checklist item representing a single step.
Did we decide to change `step` with `task`? I cannot remember anymore :joy:

2020-10-08 13:35 UTC, agarciamontoro commented on docs/glossary.md
> +* **Incident participant:** A Mattermost user with access to the corresponding incident channel.
We used "incident member" before, should we be consistent here?

2020-10-08 13:35 UTC, agarciamontoro commented on docs/incidents/ending-an-incident.md
> +The owner of the incident can end it via either a slash command or the right-hand sidebar.
I'm not exactly sure if you mean commander with "incident owner", but every incident member can end the incident.

2020-10-08 13:35 UTC, agarciamontoro commented on docs/incidents/managing-an-incident.md
> +- See the remaining steps
Nit: this is completely true, but we can also see the finished steps.

2020-10-08 13:35 UTC, agarciamontoro commented on docs/incidents/managing-an-incident.md
> +- Assign a step to self
Again, true, but we can assign the step to anyone else, too.

2020-10-08 13:35 UTC, agarciamontoro commented on docs/incidents/managing-an-incident.md
> +Members can assign any step to another member via the right-hand sidebar.
Is this redundant with the item in the list before?

2020-10-08 13:35 UTC, agarciamontoro commented on docs/incidents/managing-an-incident.md
> +Any member can assign the incident commander role to themselves in the right-hand sidebar.
Sorry for repeating myself here, but we can assign the commander also to any other person.

2020-10-08 13:35 UTC, agarciamontoro commented on docs/incidents/starting-an-incident.md
> +- Select the shield icon in the channel header, and click **+ Start Incident**
I'm ok with this, but technically, this can only be done from a channel that is not an incident channel. Also, a minor typo:
```suggestion
- Select the shield icon in the channel header, and click **+ Start Incident**.
```

2020-10-08 13:35 UTC, agarciamontoro commented on docs/incidents/starting-an-incident.md
> +An interactive dialog appears prompting the selection of a playbook and channel name. Click **Start Incident** to create an incident with the selected playbook. Only playbook members can use the play
The interactive dialog reads "Incident name", not channel name. Although you're right that it's technically the channel name. Also, there's the optional description too, but I'm ok not polluting this paragraph with that.
![image](https://user-images.githubusercontent.com/3924815/95464509-51ebcc80-097a-11eb-9995-e2ffb98d5974.png)

2020-10-08 13:35 UTC, agarciamontoro commented on docs/incidents/starting-an-incident.md
> +The creator of a playbook is automatically added as the first member and becomes the commander. The commander is responsible for adding other members to the incident as needed, and may assign a new c
```suggestion
The creator of an incident is automatically added as the first member and becomes the commander. The commander is responsible for adding other members to the incident as needed, and may assign a new commander once a member is added to the channel. To change commanders, click the current commander's name in the RHS and select the new commander. Only members of the channel may be selected as commanders. To change commander to a user who is not in the channel, first add the user to the channel.
```

2020-10-08 13:35 UTC, agarciamontoro commented on docs/telemetry.md
> +- Fields automatically generated by Rudder:
Maybe this can remove this line and have a common list, people reading this don't need to know the implementation detail that we're using Rudder.

2020-10-08 13:35 UTC, agarciamontoro commented on docs/telemetry.md
> +| Event  | Triggers   |  Information collected |
To this list, we need to add the following events:

- Restart incident
- Set assignee
- Update playbook
- Change commander
- Change stage
- Run checklist item slash command

I can provide the details on Tuesday morning (I doubt I'll have time today, I need to check what triggers each event and what information is collected).

2020-10-08 15:20 UTC, justinegeffen commented on docs/telemetry.md
> +| Event  | Triggers   |  Information collected |
Awesome. I'll add them in the meantime. 👍

2020-10-09 15:10 UTC, justinegeffen commented on docs/administrator-guide/permissions.md
> +Only members of the team in which the playbook or incident is defined have access. Additionally, membership of playbook is independent of membership in incidents:
You're absolutely correct. :)

2020-10-09 15:12 UTC, justinegeffen commented on docs/administrator-guide/permissions.md
> +Only members of the team in which the playbook or incident is defined have access. Additionally, membership of playbook is independent of membership in incidents:
```suggestion
Only members of the team in which the playbook or incident is defined have access. Playbook membership is independent of incident membership.
```

2020-10-09 15:42 UTC, justinegeffen commented on docs/glossary.md
> +* **Playbook:** A set of steps to execute as part of resolving an incident. It consists of one or more checklists, with each checklist item representing a single step.
```suggestion
* **Playbook:** A task-based process that's followed in order to resolve an incident. 
* **Tasks:** The individual steps required to complete the stages of an incident. Tasks can optionally be assigned to specific incident participants into stages.
* **Stage:** A set of tasks grouped together to achieve a specific goal of the workflow, which generally need to be completed before proceeding to the next stage of the incident resolution process.
```

2020-10-09 15:42 UTC, justinegeffen commented on docs/glossary.md
> +* **Incident participant:** A Mattermost user with access to the corresponding incident channel.
```suggestion
* **Incident member:** A Mattermost user with access to the corresponding incident channel.
```

2020-10-09 15:43 UTC, justinegeffen commented on docs/incidents/ending-an-incident.md
> +The owner of the incident can end it via either a slash command or the right-hand sidebar.
```suggestion
Incident members can end an incident via either a slash command or the right-hand sidebar.
```

2020-10-09 15:44 UTC, justinegeffen commented on docs/incidents/managing-an-incident.md
> +- See the remaining steps
```suggestion
- See the remaining steps
- See the finished steps
```

2020-10-09 15:44 UTC, justinegeffen commented on docs/incidents/managing-an-incident.md
> +Members are able to do the following via both the right-hand sidebar and the messaging interface:
```suggestion
Members are able to do the following via both the RHS and the messaging interface:
```

2020-10-09 15:46 UTC, justinegeffen commented on docs/incidents/managing-an-incident.md
> +## Assigning steps to members
```suggestion
```

2020-10-09 15:46 UTC, justinegeffen commented on docs/incidents/managing-an-incident.md
> +Members can assign any step to another member via the right-hand sidebar.
```suggestion
```

2020-10-09 15:47 UTC, justinegeffen commented on docs/incidents/managing-an-incident.md
> +Any member can assign the incident commander role to themselves in the right-hand sidebar.
```suggestion
An incident member can assign the incident commander role to themselves, or any other incident member, in the RHS.
```

2020-10-09 16:13 UTC, justinegeffen commented on docs/incidents/starting-an-incident.md
> +An interactive dialog appears prompting the selection of a playbook and channel name. Click **Start Incident** to create an incident with the selected playbook. Only playbook members can use the play
```suggestion
An interactive dialog appears prompting the selection of a playbook and incident name, which is required before you can select **Start Incident**. Only playbooks that you're a member of are listed in the **Playbook** drop-down menu.
```

2020-10-13 12:55 UTC, justinegeffen commented
@lieut-data, I'm not able to dismiss @agarciamontoro's change request although they have been implemented. If you're able to do so then I think we're good to merge so I can check formatting, rendering, content placement etc and leave time for iteration and improvements. 

@itao, does that work for you?

2020-10-13 12:59 UTC, lieut-data commented
@itao is out this week, but I suspect he'd be fine with the iteration approach. @agarciamontoro, did you want to accept these changes and iterate as such thereafter?

2020-10-13 13:05 UTC, justinegeffen commented
Ah, forgot about @itao being out. No worries. I thought @agarciamontoro was out all week but I think he's back today. :)

2020-10-13 13:21 UTC, agarciamontoro approved these changes
:tada:

2020-10-13 14:09 UTC, merged